export enum Role {
  PUBLIC = 'PUBLIC',
  AGENT_SAISIE = 'AGENT_SAISIE',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export enum Secteur {
  AGROALIMENTAIRE = 'AGROALIMENTAIRE',
  BOIS_ET_PAPETERIE = 'BOIS_ET_PAPETERIE',
  CHIMIE_ET_PHARMACIE = 'CHIMIE_ET_PHARMACIE',
  CONSTRUCTION_ET_BTP = 'CONSTRUCTION_ET_BTP',
  ENERGIE_ET_EAU = 'ENERGIE_ET_EAU',
  MECANIQUE_ET_ELECTRIQUE = 'MECANIQUE_ET_ELECTRIQUE',
  METALLURGIE_ET_SIDÉRURGIE = 'METALLURGIE_ET_SIDÉRURGIE',
  MINES_ET_CARRIERES = 'MINES_ET_CARRIERES',
  TEXTILE_ET_HABILLEMENT = 'TEXTILE_ET_HABILLEMENT',
  TIC_ET_NUMÉRIQUE = 'TIC_ET_NUMÉRIQUE',
  AUTRE = 'AUTRE'
}

export enum Region {
  CENTRE = 'CENTRE',
  LITTORAL = 'LITTORAL',
  OUEST = 'OUEST',
  NORD_OUEST = 'NORD_OUEST',
  SUD_OUEST = 'SUD_OUEST',
  EST = 'EST',
  ADAMAOUA = 'ADAMAOUA',
  NORD = 'NORD',
  EXTREME_NORD = 'EXTREME_NORD',
  SUD = 'SUD'
}

export enum StatutEntreprise {
  ACTIF = 'ACTIF',
  INACTIF = 'INACTIF',
  EN_CREATION = 'EN_CREATION',
  SUSPENDU = 'SUSPENDU'
}

export enum Periode {
  TRIMESTRIEL = 'TRIMESTRIEL',
  SEMESTRIEL = 'SEMESTRIEL',
  ANNUEL = 'ANNUEL'
}

export enum StatutValidation {
  EN_ATTENTE = 'EN_ATTENTE',
  VALIDE = 'VALIDE',
  REJETE = 'REJETE'
}

export enum TypeNote {
  CONJONCTURE = 'CONJONCTURE',
  SECTEUR = 'SECTEUR',
  REGIONALE = 'REGIONALE'
}

export enum StatutPublication {
  BROUILLON = 'BROUILLON',
  PUBLIE = 'PUBLIE',
  ARCHIVE = 'ARCHIVE'
}