      .ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-063',
      denomination: 'Camerounaise de Laiterie de l'Ouest',
      sigle: 'Camlait-Ouest',
      formeJuridique: 'SARL',
      adresse: 'Dschang',
      ville: 'Dschang',
      departement: 'Menoua',
      region: Region.OUEST,
      latitude: 5.4500,
      longitude: 10.0667,
      telephone: '+237 222 29 40 00',
      email: 'contact@camlait-ouest.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Produits laitiers',
      produitsPrincipaux: ['Lait', 'Fromage', 'Yaourt', 'Beurre'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-064',
      denomination: 'Société de Bois de l'Est',
      sigle: 'SBE',
      formeJuridique: 'SA',
      adresse: 'Bertoua',
      ville: 'Bertoua',
      departement: 'Lom-et-Djerem',
      region: Region.EST,
      latitude: 4.5833,
      longitude: 13.6833,
      telephone: '+237 222 28 80 00',
      email: 'contact@sbe-cm.com',
      secteurActivite: Secteur.BOIS_ET_PAPETERIE,
      sousSecteur: 'Exploitation forestière',
      produitsPrincipaux: ['Bois de construction', 'Grumes', 'Placages'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-065',
      denomination: 'Camerounaise de Coton de l'Extrême-Nord',
      sigle: 'Coton-EN',
      formeJuridique: 'SA',
      adresse: 'Maroua',
      ville: 'Maroua',
      departement: 'Diamaré',
      region: Region.EXTRÊME_NORD,
      latitude: 10.5917,
      longitude: 14.3158,
      telephone: '+237 222 29 50 00',
      email: 'contact@coton-en.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Coton & Textile',
      produitsPrincipaux: ['Coton', 'Fibres', 'Tourteaux', 'Huile'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-066',
      denomination: 'Camerounaise de Riziculture de l'Adamaoua',
      sigle: 'Camriz-Adamaoua',
      formeJuridique: 'SARL',
      adresse: 'Ngaoundéré',
      ville: 'Ngaoundéré',
      departement: 'Vina',
      region: Region.ADAMAOUA,
      latitude: 7.3167,
      longitude: 13.5833,
      telephone: '+237 222 29 60 00',
      email: 'contact@camriz-ad.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Riziculture',
      produitsPrincipaux: ['Riz blanc', 'Riz parfumé', 'Semences'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-067',
      denomination: 'Société de Pêche du Sud-Ouest',
      sigle: 'SPSO',
      formeJuridique: 'SARL',
      adresse: 'Limbé',
      ville: 'Limbé',
      departement: 'Fako',
      region: Region.SUD_OUEST,
      latitude: 4.0244,
      longitude: 9.2148,
      telephone: '+237 233 36 90 00',
      email: 'contact@spso-cm.com',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Pêche & Aquaculture',
      produitsPrincipaux: ['Poissons frais', 'Poissons fumés', 'Crevettes', 'Huîtres'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-068',
      denomination: 'Camerounaise de Bauxite de l'Adamaoua',
      sigle: 'Cambauxite',
      formeJuridique: 'SA',
      adresse: 'Minim-Martap',
      ville: 'Ngaoundal',
      departement: 'Djérem',
      region: Region.ADAMAOUA,
      latitude: 6.5167,
      longitude: 13.2667,
      telephone: '+237 222 25 70 00',
      email: 'contact@cambauxite.cm',
      secteurActivite: Secteur.MINES_ET_CARRIERES,
      sousSecteur: 'Bauxite',
      produitsPrincipaux: ['Bauxite', 'Alumine', 'Aluminium'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-069',
      denomination: 'Camerounaise de Fer de l'Est',
      sigle: 'Camfer-Est',
      formeJuridique: 'SA',
      adresse: 'Lomié',
      ville: 'Lomié',
      departement: 'Haut-Nyong',
      region: Region.EST,
      latitude: 3.1500,
      longitude: 13.6167,
      telephone: '+237 222 28 90 00',
      email: 'contact@camfer-est.cm',
      secteurActivite: Secteur.MINES_ET_CARRIERES,
      sousSecteur: 'Fer & Sidérurgie',
      produitsPrincipaux: ['Minerai de fer', 'Fonte', 'Acier'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-070',
      denomination: 'Société de Ciment du Nord',
      sigle: 'SCN',
      formeJuridique: 'SA',
      adresse: 'Garoua',
      ville: 'Garoua',
      departement: 'Bénoué',
      region: Region.NORD,
      latitude: 9.3000,
      longitude: 13.4000,
      telephone: '+237 222 27 30 00',
      email: 'contact@scn-cm.com',
      secteurActivite: Secteur.CONSTRUCTION_ET_BTP,
      sousSecteur: 'Ciment',
      produitsPrincipaux: ['Ciment', 'Béton', 'Granulats'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Garoua',
    },
    {
      referenceSPI: 'SPI-CAM-2026-071',
      denomination: 'Camerounaise de Plastiques',
      sigle: 'Camplast',
      formeJuridique: 'SARL',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0711,
      longitude: 9.7279,
      telephone: '+237 233 39 12 12',
      email: 'contact@camplast.cm',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Plastiques & Emballages',
      produitsPrincipaux: ['Bouteilles plastiques', 'Sachets', 'Emballages', 'Récipients'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Bonabéri',
    },
    {
      referenceSPI: 'SPI-CAM-2026-072',
      denomination: 'Société de Recyclage du Cameroun',
      sigle: 'SRC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8580,
      longitude: 11.5121,
      telephone: '+237 222 23 34 34',
      email: 'contact@src-cm.com',
      secteurActivite: Secteur.AUTRE,
      sousSecteur: 'Recyclage & Environnement',
      produitsPrincipaux: ['Plastique recyclé', 'Papier recyclé', 'Métaux recyclés', 'Compost'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-073',
      denomination: 'Camerounaise de Caoutchouc',
      sigle: 'Camcaout',
      formeJuridique: 'SA',
      adresse: 'Limbé',
      ville: 'Limbé',
      departement: 'Fako',
      region: Region.SUD_OUEST,
      latitude: 4.0244,
      longitude: 9.2148,
      telephone: '+237 233 36 10 10',
      email: 'contact@camcaout.cm',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Caoutchouc & Élastomères',
      produitsPrincipaux: ['Caoutchouc naturel', 'Pneus', 'Joints', 'Tubes'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Limbé',
    },
    {
      referenceSPI: 'SPI-CAM-2026-074',
      denomination: 'Société de Construction Navale du Cameroun',
      sigle: 'SCNC',
      formeJuridique: 'SA',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0511,
      longitude: 9.7679,
      telephone: '+237 233 42 45 45',
      email: 'contact@scnc-cm.com',
      secteurActivite: Secteur.MÉCANIQUE_ET_ELECTRIQUE,
      sousSecteur: 'Construction navale',
      produitsPrincipaux: ['Bateaux de pêche', 'Pirogues industrielles', 'Réparations navales'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Port Autonome de Douala',
    },
    {
      referenceSPI: 'SPI-CAM-2026-075',
      denomination: 'Camerounaise de Produits Pharmaceutiques',
      sigle: 'Campharm',
      formeJuridique: 'SA',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 56 56',
      email: 'contact@campharm.cm',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Pharmaceutique',
      produitsPrincipaux: ['Médicaments génériques', 'Vaccins', 'Dispositifs médicaux', 'Santé publique'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-076',
      denomination: 'Société de Transformation du Manioc',
      sigle: 'STM',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8580,
      longitude: 11.5121,
      telephone: '+237 222 23 67 67',
      email: 'contact@stm-cm.com',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Transformation du manioc',
      produitsPrincipaux: ['Farine de manioc', 'Tapioca', 'Cassave', 'Fufu industriel'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-077',
      denomination: 'Camerounaise de Produits Cosmétiques',
      sigle: 'Camcos',
      formeJuridique: 'SARL',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0611,
      longitude: 9.7779,
      telephone: '+237 233 42 56 56',
      email: 'contact@camcos.cm',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Cosmétiques & Hygiène',
      produitsPrincipaux: ['Savons', 'Shampoings', 'Crèmes', 'Produits de beauté'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Bonabéri',
    },
    {
      referenceSPI: 'SPI-CAM-2026-078',
      denomination: 'Société de Métallurgie de l'Ouest',
      sigle: 'SMO',
      formeJuridique: 'SARL',
      adresse: 'Bafoussam',
      ville: 'Bafoussam',
      departement: 'Mifi',
      region: Region.OUEST,
      latitude: 5.4667,
      longitude: 10.4167,
      telephone: '+237 222 29 70 00',
      email: 'contact@smo-cm.com',
      secteurActivite: Secteur.METALLURGIE_ET_SIDÉRURGIE,
      sousSecteur: 'Métallurgie',
      produitsPrincipaux: ['Fer forgé', 'Acier', 'Profilés', 'Quincaillerie'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-079',
      denomination: 'Camerounaise de Tissage Traditionnel',
      sigle: 'Camtiss',
      formeJuridique: 'SARL',
      adresse: 'Bamenda',
      ville: 'Bamenda',
      departement: 'Mezam',
      region: Region.NORD_OUEST,
      latitude: 5.9597,
      longitude: 10.1469,
      telephone: '+237 222 29 80 00',
      email: 'contact@camtiss.cm',
      secteurActivite: Secteur.TEXTILE_ET_HABILLEMENT,
      sousSecteur: 'Tissage traditionnel',
      produitsPrincipaux: ['Pagnes', 'Tissus traditionnels', 'Brodés', 'Accessoires textiles'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-080',
      denomination: 'Société de Production d'Énergie Solaire du Nord',
      sigle: 'SPESN',
      formeJuridique: 'SARL',
      adresse: 'Maroua',
      ville: 'Maroua',
      departement: 'Diamaré',
      region: Region.EXTRÊME_NORD,
      latitude: 10.5917,
      longitude: 14.3158,
      telephone: '+237 222 29 90 00',
      email: 'contact@spesn-cm.com',
      secteurActivite: Secteur.ÉNERGIE_ET_EAU,
      sousSecteur: 'Énergie solaire',
      produitsPrincipaux: ['Panneaux solaires', 'Lampes solaires', 'Stations de recharge', 'Énergie rurale'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-081',
      denomination: 'Camerounaise de Produits Halieutiques',
      sigle: 'Camhalieut',
      formeJuridique: 'SARL',
      adresse: 'Kribi',
      ville: 'Kribi',
      departement: 'Océan',
      region: Region.SUD,
      latitude: 2.9333,
      longitude: 9.9167,
      telephone: '+237 233 36 20 20',
      email: 'contact@camhalieut.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Pêche & Aquaculture',
      produitsPrincipaux: ['Poissons transformés', 'Conserves', 'Farine de poisson', 'Huile de poisson'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Kribi',
    },
    {
      referenceSPI: 'SPI-CAM-2026-082',
      denomination: 'Société de Transformation du Cacao de l'Est',
      sigle: 'STCE',
      formeJuridique: 'SA',
      adresse: 'Bertoua',
      ville: 'Bertoua',
      departement: 'Lom-et-Djerem',
      region: Region.EST,
      latitude: 4.5833,
      longitude: 13.6833,
      telephone: '+237 222 28 30 30',
      email: 'contact@stce-cm.com',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Cacao & Chocolat',
      produitsPrincipaux: ['Pâte de cacao', 'Beurre de cacao', 'Chocolat', 'Poudre de cacao'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-083',
      denomination: 'Camerounaise de Produits Laitiers du Nord',
      sigle: 'Camlait-Nord',
      formeJuridique: 'SARL',
      adresse: 'Garoua',
      ville: 'Garoua',
      departement: 'Bénoué',
      region: Region.NORD,
      latitude: 9.3000,
      longitude: 13.4000,
      telephone: '+237 222 27 40 40',
      email: 'contact@camlait-nord.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Produits laitiers',
      produitsPrincipaux: ['Lait', 'Fromage', 'Yaourt', 'Beurre'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-084',
      denomination: 'Société de Production d'Engrais du Centre',
      sigle: 'SPEC',
      formeJuridique: 'SA',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 78 78',
      email: 'contact@spec-cm.com',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Engrais & Agrochimie',
      produitsPrincipaux: ['Engrais NPK', 'Urée', 'Phosphates', 'Bioengrais'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-085',
      denomination: 'Camerounaise de Matériel Agricole',
      sigle: 'Cammagri',
      formeJuridique: 'SARL',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0711,
      longitude: 9.7179,
      telephone: '+237 233 39 13 13',
      email: 'contact@cammagri.cm',
      secteurActivite: Secteur.MÉCANIQUE_ET_ELECTRIQUE,
      sousSecteur: 'Matériel agricole',
      produitsPrincipaux: ['Tracteurs', 'Motoculteurs', 'Semoirs', 'Moissonneuses', 'Irrigation'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Bonabéri',
    },
    {
      referenceSPI: 'SPI-CAM-2026-086',
      denomination: 'Société de Transformation du Café de l'Ouest',
      sigle: 'STCF-Ouest',
      formeJuridique: 'SARL',
      adresse: 'Bafoussam',
      ville: 'Bafoussam',
      departement: 'Mifi',
      region: Region.OUEST,
      latitude: 5.4667,
      longitude: 10.4167,
      telephone: '+237 222 29 11 11',
      email: 'contact@stcf-ouest.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Café torréfié',
      produitsPrincipaux: ['Café torréfié', 'Café moulu', 'Café soluble', 'Café en capsules'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-087',
      denomination: 'Camerounaise de Boissons de l'Ouest',
      sigle: 'Cambev-Ouest',
      formeJuridique: 'SARL',
      adresse: 'Dschang',
      ville: 'Dschang',
      departement: 'Menoua',
      region: Region.OUEST,
      latitude: 5.4500,
      longitude: 10.0667,
      telephone: '+237 222 29 22 22',
      email: 'contact@cambev-ouest.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Boissons',
      produitsPrincipaux: ['Jus de fruits', 'Eau minérale', 'Boissons énergisantes', 'Sirops'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-088',
      denomination: 'Société de Construction de Routes du Cameroun',
      sigle: 'SCRC',
      formeJuridique: 'SA',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 89 89',
      email: 'contact@scrc-cm.com',
      secteurActivite: Secteur.CONSTRUCTION_ET_BTP,
      sousSecteur: 'Construction de routes',
      produitsPrincipaux: ['Routes', 'Ponts', 'Ouvrages d'art', 'Terrassements'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-089',
      denomination: 'Camerounaise de Produits de Soudure',
      sigle: 'Camsoud',
      formeJuridique: 'SARL',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0611,
      longitude: 9.7779,
      telephone: '+237 233 42 67 67',
      email: 'contact@camsoud.cm',
      secteurActivite: Secteur.METALLURGIE_ET_SIDÉRURGIE,
      sousSecteur: 'Soudure & Brasage',
      produitsPrincipaux: ['Électrodes', 'Fil de soudure', 'Gaz de soudure', 'Équipements de soudure'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Bonabéri',
    },
    {
      referenceSPI: 'SPI-CAM-2026-090',
      denomination: 'Société de Maintenance Électrique du Cameroun',
      sigle: 'SMEC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8580,
      longitude: 11.5121,
      telephone: '+237 222 23 90 90',
      email: 'contact@smec-cm.com',
      secteurActivite: Secteur.MÉCANIQUE_ET_ELECTRIQUE,
      sousSecteur: 'Maintenance électrique',
      produitsPrincipaux: ['Maintenance', 'Réparation', 'Installation électrique', 'Audit énergétique'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-091',
      denomination: 'Camerounaise de Télécommunications Rurales',
      sigle: 'Camtel-Rural',
      formeJuridique: 'SARL',
      adresse: 'Bamenda',
      ville: 'Bamenda',
      departement: 'Mezam',
      region: Region.NORD_OUEST,
      latitude: 5.9597,
      longitude: 10.1469,
      telephone: '+237 222 29 33 33',
      email: 'contact@camtel-rural.cm',
      secteurActivite: Secteur.TIC_ET_NUMÉRIQUE,
      sousSecteur: 'Télécommunications rurales',
      produitsPrincipaux: ['Internet rural', 'Téléphonie fixe', 'Bornes WiFi', 'Cybercentres'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-092',
      denomination: 'Société de Production de Biogaz du Cameroun',
      sigle: 'SPBC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 01 01',
      email: 'contact@spbc-cm.com',
      secteurActivite: Secteur.ÉNERGIE_ET_EAU,
      sousSecteur: 'Biogaz & Biomasse',
      produitsPrincipaux: ['Biogaz', 'Digestats', 'Énergie verte', 'Stations de biométhanisation'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-093',
      denomination: 'Camerounaise de Produits de Bambou',
      sigle: 'Cambambou',
      formeJuridique: 'SARL',
      adresse: 'Bafoussam',
      ville: 'Bafoussam',
      departement: 'Mifi',
      region: Region.OUEST,
      latitude: 5.4667,
      longitude: 10.4167,
      telephone: '+237 222 29 44 44',
      email: 'contact@cambambou.cm',
      secteurActivite: Secteur.BOIS_ET_PAPETERIE,
      sousSecteur: 'Bambou & Articles en bambou',
      produitsPrincipaux: ['Meubles en bambou', 'Construction bambou', 'Artisanat', 'Papier bambou'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-094',
      denomination: 'Société de Transformation du Miel du Cameroun',
      sigle: 'STMC',
      formeJuridique: 'SARL',
      adresse: 'Garoua',
      ville: 'Garoua',
      departement: 'Bénoué',
      region: Region.NORD,
      latitude: 9.3000,
      longitude: 13.4000,
      telephone: '+237 222 27 50 50',
      email: 'contact@stmc-cm.com',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Apiculture',
      produitsPrincipaux: ['Miel', 'Cire d'abeille', 'Propolis', 'Gelée royale'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-095',
      denomination: 'Camerounaise de Produits de Karité',
      sigle: 'Camkarité',
      formeJuridique: 'SARL',
      adresse: 'Maroua',
      ville: 'Maroua',
      departement: 'Diamaré',
      region: Region.EXTRÊME_NORD,
      latitude: 10.5917,
      longitude: 14.3158,
      telephone: '+237 222 29 55 55',
      email: 'contact@camkarite.cm',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Karité & Cosmétiques naturels',
      produitsPrincipaux: ['Beurre de karité', 'Huile de karité', 'Cosmétiques naturels', 'Savons'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-096',
      denomination: 'Société de Production de Spiruline du Cameroun',
      sigle: 'SPSC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 02 02',
      email: 'contact@spsc-cm.com',
      secteurActivite: Secteur.AGROALIMENTAIRE,
      sousSecteur: 'Nutrition & Compléments alimentaires',
      produitsPrincipaux: ['Spiruline', 'Compléments alimentaires', 'Protéines végétales', 'Nutraceutiques'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-097',
      denomination: 'Camerounaise de Matériel Médical',
      sigle: 'Cammmed',
      formeJuridique: 'SARL',
      adresse: 'Douala',
      ville: 'Douala',
      departement: 'Wouri',
      region: Region.LITTORAL,
      latitude: 4.0711,
      longitude: 9.7179,
      telephone: '+237 233 39 14 14',
      email: 'contact@cammmed.cm',
      secteurActivite: Secteur.CHIMIE_ET_PHARMACIE,
      sousSecteur: 'Dispositifs médicaux',
      produitsPrincipaux: ['Matériel médical', 'Orthopédie', 'Prothèses', 'Équipements hospitaliers'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: true,
      nomZoneIndustrielle: 'Zone Industrielle Bonabéri',
    },
    {
      referenceSPI: 'SPI-CAM-2026-098',
      denomination: 'Société de Recyclage Électronique du Cameroun',
      sigle: 'SREC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8580,
      longitude: 11.5121,
      telephone: '+237 222 23 03 03',
      email: 'contact@srec-cm.com',
      secteurActivite: Secteur.TIC_ET_NUMÉRIQUE,
      sousSecteur: 'Recyclage électronique',
      produitsPrincipaux: ['Recyclage téléphones', 'Recyclage ordinateurs', 'Récupération métaux rares', 'Réparation'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: false,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-099',
      denomination: 'Camerounaise de Produits de l'Artisanat Numérique',
      sigle: 'Camartnum',
      formeJuridique: 'SARL',
      adresse: 'Bamenda',
      ville: 'Bamenda',
      departement: 'Mezam',
      region: Region.NORD_OUEST,
      latitude: 5.9597,
      longitude: 10.1469,
      telephone: '+237 222 29 66 66',
      email: 'contact@camartnum.cm',
      secteurActivite: Secteur.TIC_ET_NUMÉRIQUE,
      sousSecteur: 'Artisanat numérique & Impression 3D',
      produitsPrincipaux: ['Impression 3D', 'Design numérique', 'Prototypage', 'FabLab'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
    {
      referenceSPI: 'SPI-CAM-2026-100',
      denomination: 'Société de Production de Films et Médias du Cameroun',
      sigle: 'SPFMC',
      formeJuridique: 'SARL',
      adresse: 'Yaoundé',
      ville: 'Yaoundé',
      departement: 'Mfoundi',
      region: Region.CENTRE,
      latitude: 3.8480,
      longitude: 11.5021,
      telephone: '+237 222 23 04 04',
      email: 'contact@spfmc-cm.com',
      secteurActivite: Secteur.TIC_ET_NUMÉRIQUE,
      sousSecteur: 'Production audiovisuelle',
      produitsPrincipaux: ['Films', 'Séries TV', 'Publicités', 'Contenus digitaux', 'Animation'],
      statut: StatutEntreprise.ACTIF,
      estExportateur: true,
      estDansZoneIndustrielle: false,
    },
  ];

  // Création des entreprises
  for (const entreprise of entreprisesData) {
    await prisma.entreprise.create({
      data: entreprise,
    });
  }

  console.log(`✅ ${entreprisesData.length} entreprises créées`);

  // ============================================================
  // 3. CONFIGURATION SYSTÈME
  // ============================================================
  await prisma.configSystem.create({
    data: {
      anneeEnCours: 2026,
      seuilAlerteProduction: 20.0,
      seuilAlerteEmplois: 15.0,
      emailNotifications: 'admin@spi-cam.cm',
      frequenceRappelSaisie: '0 0 1 * *', // 1er de chaque mois
      maintenanceMode: false,
    },
  });

  console.log('✅ Configuration système initialisée');

  // ============================================================
  // 4. DONNÉES DE PRODUCTION DE TEST (T1 2026)
  // ============================================================
  const entreprises = await prisma.entreprise.findMany();
  const agent = users.find(u => u.role === 'AGENT_SAISIE');

  for (const entreprise of entreprises.slice(0, 20)) { // 20 premières entreprises avec données
    await prisma.productionData.create({
      data: {
        annee: 2026,
        periode: 'TRIMESTRIEL',
        trimestre: 1,
        volumeProduit: Math.floor(Math.random() * 10000) + 1000,
        uniteMesure: 'tonnes',
        valeurProduction: Math.floor(Math.random() * 1000000000) + 100000000,
        chiffreAffaires: Math.floor(Math.random() * 1200000000) + 100000000,
        nombreEmployes: Math.floor(Math.random() * 500) + 50,
        capaciteInstallee: Math.floor(Math.random() * 15000) + 5000,
        capaciteUtilisee: Math.floor(Math.random() * 40) + 60,
        tauxQualite: Math.floor(Math.random() * 10) + 90,
        tauxDisponibilite: Math.floor(Math.random() * 15) + 85,
        volumeExport: Math.floor(Math.random() * 2000),
        valeurExport: Math.floor(Math.random() * 200000000),
        paysDestination: ['France', 'Belgique', 'Nigeria', 'Gabon'],
        matieresPremieresLocal: Math.floor(Math.random() * 30) + 70,
        matieresPremieresImport: Math.floor(Math.random() * 30),
        sourceDonnee: 'Déclaration entreprise',
        methodeCollecte: 'Questionnaire en ligne',
        saisieParId: agent!.id,
        statutValidation: 'VALIDE',
        validePar: users.find(u => u.role === 'ADMIN')!.id,
        dateValidation: new Date(),
        entrepriseId: entreprise.id,
      },
    });
  }

  console.log('✅ 20 données de production de test créées (T1 2026)');

  console.log('\n🎉 Seeding terminé avec succès !');
  console.log('\n👤 Utilisateurs de test :');
  console.log('   • superadmin@spi-cam.cm / SpiCam2026! (SUPER_ADMIN)');
  console.log('   • admin@spi-cam.cm / SpiCam2026! (ADMIN)');
  console.log('   • agent1@spi-cam.cm / SpiCam2026! (AGENT_SAISIE)');
  console.log('   • agent2@spi-cam.cm / SpiCam2026! (AGENT_SAISIE)');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
